config/routes.rb
Myreplicator::Engine.routes.draw do
  resources :exports
  root :to => "home#index"
  match '/export_errors', :to => "home#export_errors", :as => 'export_errors'
  match '/transport_errors', :to => "home#transport_errors", :as => 'transport_errors'
  match '/load_errors', :to => "home#load_errors", :as => 'load_errors'
  match '/kill/:id', :to => 'home#kill', :as => 'kill'
  match '/search', :to => "exports#search"
  
  resources :home do
    get :pause, :on => :collection
    get :resume, :on => :collection
  end
  
  resources :exports do
    get :search, :on => :collection
    member do
      get 'reload'
    end
  end
end

app/models/myreplicator/log.rb
module Myreplicator
  class Log < ActiveRecord::Base
    attr_accessible(:pid,
                    :job_type,
                    :name,
                    :file,
                    :state,
                    :thread_state,
                    :hostname,
                    :export_id,
                    :error,
                    :backtrace,
                    :guid,
                    :started_at,
                    :finished_at)
    
    ##
    # Creates a log object
    # Stores the state and related information about the job
    # File's names are supposed to be unique
    ##
    def self.run *args
      options = args.extract_options!
      options.reverse_merge!(:started_at => Time.now,
                             :pid => Process.pid,
                             :hostname => Socket.gethostname,
                             :guid => SecureRandom.hex(5),
                             :thread_state => Thread.current.to_s,
                             :state => "new")

      log = Log.create options

      if  !log.running?
        begin
          log.state = "running"
          log.save!

          yield log

          log.state = "completed"
        rescue Exception => e
          log.state = "error"
          log.error = e.message
          log.backtrace =  e.backtrace

        ensure
          log.finished_at = Time.now
          log.save!
        end
      else
        begin
          log.state = "ignored"
        rescue Exception => e
          log.state = "error"
          log.error = e.message
          log.backtrace =  e.backtrace
        ensure
          log.finished_at = Time.now
          log.save!
        end
      end

    end

    ##
    # Kills the job if running
    # Using PID
    ##
    def kill
      return false unless hostname == Socket.gethostname
      begin
        Process.kill('KILL', pid)
        self.state = "killed"
        self.save!
      rescue Errno::ESRCH
        puts "pid #{pid} does not exist!"
        mark_dead
      end
    end

    ##
    # Checks to see if the PID of the log is active or not
    ##
    def running?
      logs = Log.where(:file => file, 
                       :job_type => job_type, 
                       :state => "running",
                       :export_id => export_id,
                       :hostname => hostname)
  
      if logs.count > 0
        logs.each do |log|
          begin
            Process.getpgid(log.pid)
            puts "still running #{log.file}"
            return true
          rescue Errno::ESRCH
            log.mark_dead
          end
        end
      end
      
      return false
    end
    
    ##
    # Clear all logs marked running that have run for more than 2 hours
    ##
    def self.clear_stucks
      runnings = Log.where(:state => "running")
      news = Log.where(:state => "new")
      logs = runnings + news
      
      if logs.count > 0
        logs.each do |log|
          
          time_start = log.started_at
          now = Time.now()
          if time_start + 2.hour < now
            begin
              Process.kill('KILL', log.pid)
              log.state = "killed"
              log.save!
            rescue Errno::ESRCH
              log.state = "dead"
              log.save!
            end  
          end
        end
      end
      
    end

    
    ##
    # Clear all logs marked running that are not running
    ##
    def self.clear_deads
      logs = Log.where(:state => "running")
  
      if logs.count > 0
        logs.each do |log|
          begin
            Process.getpgid(log.pid) if log.hostname == Socket.gethostname
          rescue Errno::ESRCH
            log.mark_dead
          end
        end
      end
      
    end

    def self.clear_olds
      logs = Myreplicator::Log.where("started_at < date_sub(now(), interval 2 day)")
  
      if logs.count > 0
        logs.each do |log|
          begin
            log.destroy
          end
        end
      end
      
    end

    ##
    # Gets a jobtype, file and export_id
    # returns true if the job is completed
    ##
    def self.completed? *args
      options = args.extract_options!
      log = Log.where(:export_id => options[:export_id],
                      :file => options[:file],
                      :job_type => options[:job_type]).last
      #Kernel.p "===== transport_complete? log ====="
      #Kernel.p log
      if log.nil?
        #return false
        # Bug: no log of tranporter job. Using return true for now
        return true
      else
        return true if log.state == "completed"
      end
      
      return false
    end

    def mark_dead
      self.state = "dead"
      self.save!
    end

  end
end

app/models/myreplicator/sweeper.rb
module Myreplicator
  class Sweeper

    @queue = :myreplicator_sweeper # Provided for Resque
    ##
    # Main method provided for resque
    # Reconnection provided for resque workers
    ##
    def self.perform
      Myreplicator::Log.clear_deads
      Myreplicator::Log.clear_stucks
      Myreplicator::Log.clear_olds
      ActiveRecord::Base.configurations.keys.each do |db|
        Myreplicator::VerticaLoader.clean_up_temp_tables(db)
      end

      #removing files that are left in the storage for more than 12 hours
      folders = [
        "#{Myreplicator.tmp_path}",
        "#{Myreplicator.configs[Myreplicator.configs.keys[1]]["ssh_tmp_dir"]}"
      ]

      folders.each do |folder|
        cmd = "find #{folder} -mmin +720"
        l = `#{cmd}`
        list = l.split(/\n/)
        list.each do |file|
          file.chomp!
          if File.file?(file)
            if (file.split('.').last == 'gz') || (file.split('.').last == 'json')
              puts "=== #{file}"
              File.delete(file)
            end
          end
        end
      end

    end

  end
end

app/models/myreplicator/transfer.rb
module Myreplicator
  class Transfer < ActiveRecord::Base
    # attr_accessible :title, :body
  end
end

app/models/myreplicator/vertica_export.rb
module Myreplicator
  class VerticaExport < ActiveRecord::Base
    # attr_accessible :title, :body
  end
end

app/controllers/myreplicator/application_controller.rb
module Myreplicator
  class ApplicationController < ActionController::Base
    before_filter :authenticated?
    
    private 
    
    def authenticated?
      Kernel.p Myreplicator.auth_required
      if Myreplicator.auth_required
        puts request.fullpath
        url = "#{Myreplicator.login_redirect}?redirect_url=#{request.fullpath}"
        redirect_to url unless Myreplicator.authenticated
      end
    end
    
  end
end

app/controllers/myreplicator/exports_controller.rb
require_dependency "myreplicator/application_controller"

module Myreplicator

  class ExportsController < ApplicationController
    before_filter :tab
    helper_method :sort_column, :sort_direction
    # GET /exports
    # GET /exports.json
    def index
      @exports = Export.paginate(:page => params[:page]).order(sort_column + " " + sort_direction)
      @export = Export.first
      @dbs = get_dbs
      @search = Export.first
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @exports }
      end
      
    end
    
    def search
      Kernel.p params
      export_to = params[:export_to]
      table_name = params[:table_name]
      @exports = Export.paginate(:page => params[:page]).where("table_name LIKE '%#{table_name}%'")
      Kernel.p @exports.size 
      @search = Export.first
      @dbs = get_dbs
      @export = Export.first
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @exports }
      end
    end
  
    # GET /exports/1
    # GET /exports/1.json
    def show
      @export = Export.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @export }
      end
    end
  
    # GET /exports/new
    # GET /exports/new.json
    def new
      @export = Export.new
      @dbs = get_dbs
      @tables = db_metadata
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @export }
      end
    end
  
    # GET /exports/1/edit
    def edit
      @export = Export.find(params[:id])
      @dbs = get_dbs
      @tables = db_metadata
      @edit = true
    end
  
    # POST /exports
    # POST /exports.json
    def create
      @export = Export.new(params[:export])
      @dbs = get_dbs
      respond_to do |format|
        if @export.save
          format.html { redirect_to @export, notice: 'Export was successfully created.' }
          format.json { render json: @export, status: :created, location: @export }
          Myreplicator::Export.schedule_in_resque # schedule in resque
        else
          format.html { render action: "new" }
          format.json { render json: @export.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /exports/1
    # PUT /exports/1.json
    def update
      @export = Export.find(params[:id])
      @dbs = get_dbs
  
      respond_to do |format|
        if @export.update_attributes(params[:export])
          format.html { redirect_to @export, notice: 'Export was successfully updated.' }
          format.json { head :no_content }
          Myreplicator::Export.schedule_in_resque # schedule in resque
        else
          format.html { render action: "edit" }
          format.json { render json: @export.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /exports/1
    # DELETE /exports/1.json
    def destroy
      @export = Export.find(params[:id])

      # remove from Resque
      Resque.remove_schedule(@export.schedule_name)

      @export.destroy

      respond_to do |format|
        format.html { redirect_to exports_url }
        format.json { head :no_content }
      end
    end
    
    def reload
      @export = Export.find(params[:id])
      flash[:notice] = "'#{@export.destination_schema}.#{@export.table_name}' is reloading"
      @export.reload
      redirect_to :action => 'index'
    end

  private

    def tab
      @tab = "exports"
    end
  
    def sort_column
      Export.column_names.include?(params[:sort]) ? params[:sort] : "source_schema"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
    def db_metadata
      @db_metadata ||= Myreplicator::Export.available_tables
    end

    def get_dbs
      return db_metadata.keys
    end

    def get_tables(db)
      return db_metadata[db]
    end
  end
end

app/controllers/myreplicator/home_controller.rb
require_dependency "myreplicator/application_controller"

module Myreplicator

  class HomeController < ApplicationController
    def index  
      @tab = 'home'
      @option = 'overview'
      @exports = Export.order('state DESC')
      @logs = Log.where(:state => 'running').order("id DESC")
      @now = Time.zone.now
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @exports }
      end
    end

    def export_errors
      @tab = 'home'
      @option = 'errors'
      @exports = Export.where("error is not null").order('source_schema ASC')    
      @logs = Log.where("state = 'error' AND job_type = 'export'").order("id DESC").limit(200)
      @count = Log.where("state = 'error' AND job_type = 'export'").count
    end
    
    def transport_errors
      @tab = 'home'
      @option = 'errors'
      @logs = Log.where("state = 'error' AND job_type = 'transporter'").order("id DESC").limit(200)
      @count = Log.where("state = 'error' AND job_type = 'transporter'").count
    end

    def load_errors
      @tab = 'home'
      @option = 'errors'
      @logs = Log.where("state = 'error' AND job_type = 'loader'").order("id DESC").limit(200)
      @count = Log.where("state = 'error' AND job_type = 'loader'").count
    end
    

    def kill
      @log = Log.find(params[:id])
      @log.kill
      redirect_to :action => 'index' 
    end
    
    def pause
      flash[:notice] = "Pause All DR Jobs"
      require 'rake'
      Rake::Task.load(Rails.root.to_s + "/lib/tasks/" + "maintenance.rake")
      resque_reload = Rake::Task['maintenance:stop_dr_jobs']
      resque_reload.reenable
      resque_reload.execute(ENV["RAILS_ENV"])
      @redis = Redis.new(:host => Settings[:redis][:host], :port => Settings[:redis][:port])
      @redis.set "under_maintenance", "true"
      redirect_to :action => 'index'
    end
        
    def resume
      flash[:notice] = "Resume All DR Jobs"
      require 'rake'
      Rake::Task.load(Rails.root.to_s + "/lib/tasks/" + "maintenance.rake")
      resque_reload = Rake::Task['maintenance:start_dr_jobs']
      resque_reload.reenable
      resque_reload.execute(ENV["RAILS_ENV"])
      @redis = Redis.new(:host => Settings[:redis][:host], :port => Settings[:redis][:port])
      @redis.set "under_maintenance", "false"
      redirect_to :action => 'index'
    end
  end
end

app/helpers/myreplicator/application_helper.rb
module Myreplicator
  module ApplicationHelper

    def sortable(column, title = nil)
      title ||= column.titleize
      css_class = column == sort_column ? "current #{sort_direction}" : nil
      direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
      link_to content_tag(:span, title), {:sort => column, :direction => direction}, {:class => css_class}
    end

    def chronos(secs)
      [[60, :seconds], [60, :minutes], [24, :hours], [1000, :days]].map{ |count, name|
        if secs > 0
          secs, n = secs.divmod(count)
          "#{n.to_i} #{name}"
        end
      }.compact.reverse.join(', ')
    end

    def export_err_count
      count = Log.where("state = 'error' AND job_type = 'export'").count
    end


    def run_count
      total = Log.where(:state => 'running').count
    end

    def loader_err_count
      count = Log.where("state = 'error' AND job_type = 'loader'").count
    end
    
    def transporter_err_count
      count = Log.where("state = 'error' AND job_type = 'transporter'").count
    end
    
    def under_maintenance
      #@redis = Redis.new(:host => 'localhost', :port => 6379)
      @redis = Redis.new(:host => Settings[:redis][:host], :port => Settings[:redis][:port])
      tmp = @redis.get "under_maintenance"
      puts tmp.class
      if tmp == "true"
        puts "===== ADASHKJDHJASKHDLASJLKDJALKS ====="
        puts tmp
        return true
      end
      return false
    end
    
  end
end

app/helpers/myreplicator/exports_helper.rb
module Myreplicator
  module ExportsHelper
  end
end

app/views/myreplicator/exports/edit.html.erb
<h2>Edit Export</h2>
<%= render 'form' %>

app/views/myreplicator/exports/index.html.erb
<%
export_type = ["incremental","all"]
export_to = ["destination_db","backup","vertica"]
%>
<%= link_to content_tag(:span, 'add export'), new_export_path, :class => "btn right main add" %>

<div class = "search_box">

	<div id="menu" >
		<h2>Exports</h2>
	</div>

	<div id="content">

		<%= form_tag("/myreplicator/search", method: "get") do %>
  			
  			<div id = "search_form">
			<label>Export to</label>
			<select name="export[export_to]" id = "drop_down">
  				<% export_to.each do |val| %>
  					<option value="<%= val %>" SELECTED><%= val %></option>
  				<% end %> 
			</select>
			</div>
			<div id = "search_form">
			<label>Source Schema</label>
			<select name="export[source_schema]" id = "drop_down">
  				<% @dbs.each do |val| %>
  					<option value="<%= val %>" SELECTED><%= val %></option>
  				<% end %>
			</select>
			</div>
			<div id = "text_box">
				<label>Table Name</label>
				<%= text_field_tag(:table_name) %>
			</div>
			
  			
		<% end %>  
</div>
</div>

<%= will_paginate @exports , :previous_label => '<', :next_label => '>', :inner_window => 2, :outer_window => 0%>
<% if @exports.total_entries > @exports.per_page %>
<div id="pagination-display-message">Displaying <%= @exports.offset + 1 %> - <%= @exports.offset + @exports.length %> of <%= pluralize(@exports.total_entries, 'exports') %></div>
<% end %>
<div class="table-wrapper">
  <table class="data-grid">
    <thead>
      <tr>
       <th><%= sortable "export_type" %></th> 
       <th><%= sortable "export_to", "Export Desitination" %></th>       
       <th colspan="2"><%= sortable "source_schema" %></th>
       <th><%= sortable "destination_schema" %></th>
       <th><%= sortable "table_name" %></th>
       <th><%= sortable "incremental_column" %></th>
       <th><%= sortable "incremental_column_type" %></th>
       <th><%= sortable "max_incremental_value" %></th>
       <th><%= sortable "s3_path" %></th>
       <th><%= sortable "cron" %></th> 
       <th class="center">Actions</th>
       <th class="center">Utils</th>
      </tr>
    </thead>
    <tbody>
    <% @exports.each do |export| %>
      <tr>
        <td><%= export.export_type %></td> 
        <td><%= export.export_to %></td>        
        <td class="state"><span class="status <% if export.active %>active<% else %>inactive<% end %>" title="<% if export.active %>Active<% else %>Inactive<% end %>"></span></td> 
        <td class="source"><%= export.source_schema %></td>
        <td><%= export.destination_schema %></td>
        <td><%= export.table_name %></td>
        <td><%= export.incremental_column %></td>
        <td><%= export.incremental_column_type %></td>
        <td><%= export.max_incremental_value %></td>
        <td><%= export.s3_path %></td>
        <td><span class="cron" data-cron="<%= export.cron %>" title=""><%= export.cron %></span></td>     
        <td>
          <%= link_to 'review', export, :class=> 'action view' %>
          <%= link_to 'edit', edit_export_path(export), :class => 'action edit' %>
          <%= link_to 'destroy', export, method: :delete, data: { confirm: 'Are you sure?' }, :class=> 'action delete' %>
        </td>
        <td>
          <%= link_to 'reload', reload_export_path(export), :class=> 'action edit' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<script>
$(function(){
  $.each($("span.cron"),function(i){
    var span = $(this)
    var trans = String(CronWTF.parse(span.data("cron")));
    span.attr("title", trans)
  })
  $("span.status").tipTip();
  $("span.cron").tipTip();
})
</script>

app/views/myreplicator/exports/new.html.erb
<h2>New Export</h2>
<%= render 'form' %>

app/views/myreplicator/exports/search.html.erb
<%
export_type = ["incremental","all"]
export_to = ["destination_db","backup","vertica"]
%>
<%= link_to content_tag(:span, 'add export'), new_export_path, :class => "btn right main add" %>

<div class = "search_box">

	<div id="menu" >
		<h2>Exports</h2>
	</div>

	<div id="content">

		<%= form_tag("/myreplicator/search", method: "get") do %>
  			
  			<div id = "search_form">
			<label>Export to</label>
			<select name="export[export_to]" id = "drop_down">
  				<% export_to.each do |val| %>
  					<option value="<%= val %>" SELECTED><%= val %></option>
  				<% end %> 
			</select>
			</div>
			<div id = "search_form">
			<label>Source Schema</label>
			<select name="export[source_schema]" id = "drop_down">
  				<% @dbs.each do |val| %>
  					<option value="<%= val %>" SELECTED><%= val %></option>
  				<% end %>
			</select>
			</div>
			<div id = "text_box">
				<label>Table Name</label>
				<%= text_field_tag(:table_name) %>
			</div>
			
  			
		<% end %>  
</div>
</div>

<%= will_paginate @exports , :previous_label => '<', :next_label => '>', :inner_window => 2, :outer_window => 0%>
<% if @exports.total_entries > @exports.per_page %>
<div id="pagination-display-message">Displaying <%= @exports.offset + 1 %> - <%= @exports.offset + @exports.length %> of <%= pluralize(@exports.total_entries, 'exports') %></div>
<% end %>
<div class="table-wrapper">
  <table class="data-grid">
    <thead>
      <tr>
       <th><%= sortable "export_type" %></th> 
       <th><%= sortable "export_to", "Export Desitination" %></th>       
       <th colspan="2"><%= sortable "source_schema" %></th>
       <th><%= sortable "destination_schema" %></th>
       <th><%= sortable "table_name" %></th>
       <th><%= sortable "incremental_column" %></th>
       <th><%= sortable "incremental_column_type" %></th>
       <th><%= sortable "max_incremental_value" %></th>
       <th><%= sortable "s3_path" %></th>
       <th><%= sortable "cron" %></th> 
       <th class="center">Actions</th>
       <th class="center">Utils</th>
      </tr>
    </thead>
    <tbody>
    <% @exports.each do |export| %>
      <tr>
        <td><%= export.export_type %></td> 
        <td><%= export.export_to %></td>        
        <td class="state"><span class="status <% if export.active %>active<% else %>inactive<% end %>" title="<% if export.active %>Active<% else %>Inactive<% end %>"></span></td> 
        <td class="source"><%= export.source_schema %></td>
        <td><%= export.destination_schema %></td>
        <td><%= export.table_name %></td>
        <td><%= export.incremental_column %></td>
        <td><%= export.incremental_column_type %></td>
        <td><%= export.max_incremental_value %></td>
        <td><%= export.s3_path %></td>
        <td><span class="cron" data-cron="<%= export.cron %>" title=""><%= export.cron %></span></td>     
        <td>
          <%= link_to 'review', export, :class=> 'action view' %>
          <%= link_to 'edit', edit_export_path(export), :class => 'action edit' %>
          <%= link_to 'destroy', export, method: :delete, data: { confirm: 'Are you sure?' }, :class=> 'action delete' %>
        </td>
        <td>
          <%= link_to 'reload', reload_export_path(export), :class=> 'action edit' %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<script>
$(function(){
  $.each($("span.cron"),function(i){
    var span = $(this)
    var trans = String(CronWTF.parse(span.data("cron")));
    span.attr("title", trans)
  })
  $("span.status").tipTip();
  $("span.cron").tipTip();
})
</script>

app/views/myreplicator/exports/show.html.erb
<%= link_to content_tag(:span, 'edit export'), edit_export_path(@export), :class =>'btn right main edit' %>
<h2>Review Export</h2>
<ul id="export-review">
  <% @export.attributes.sort{|a,b| a[0] <=> b[0]}.each do |key,val| %>
    <% type = @export.column_for_attribute(key).type %>
    <li><span><%= key.gsub("_"," ") %> : </span>
      <%- if type == :datetime -%>
        <%- unless val.blank? -%>
          <%= val.strftime("%B #{val.day.ordinalize}, %Y %I:%M %p") -%>
        <%- end -%>
      <%- else -%>
        <% if key == 'cron' %>
          <em class="cron" data-cron="<%= val %>" title=""><%= val %></em>
        <%- else -%>
          <%= val -%>
        <%- end -%>
      <%- end -%>
    </li>
  <% end %>
</ul>
<script>
$(function(){
  var span = $("em.cron")
  var trans = String(CronWTF.parse(span.data("cron")));
  span.attr("title", trans)
  $("em.cron").tipTip();
})
</script>