config/routes.rb
Myreplicator::Engine.routes.draw do
  resources :exports
  root :to => "home#index"
  match '/export_errors', :to => "home#export_errors", :as => 'export_errors'
  match '/transport_errors', :to => "home#transport_errors", :as => 'transport_errors'
  match '/load_errors', :to => "home#load_errors", :as => 'load_errors'
  match '/kill/:id', :to => 'home#kill', :as => 'kill'
  match '/search', :to => "exports#search"
  
  resources :home do
    get :pause, :on => :collection
    get :resume, :on => :collection
  end
  
  resources :exports do
    get :search, :on => :collection
    member do
      get 'reload'
    end
  end
end

app/models/myreplicator/log.rb
module Myreplicator
  class Log < ActiveRecord::Base
    attr_accessible(:pid,
                    :job_type,
                    :name,
                    :file,
                    :state,
                    :thread_state,
                    :hostname,
                    :export_id,
                    :error,
                    :backtrace,
                    :guid,
                    :started_at,
                    :finished_at)
    
    ##
    # Creates a log object
    # Stores the state and related information about the job
    # File's names are supposed to be unique
    ##
    def self.run *args
      options = args.extract_options!
      options.reverse_merge!(:started_at => Time.now,
                             :pid => Process.pid,
                             :hostname => Socket.gethostname,
                             :guid => SecureRandom.hex(5),
                             :thread_state => Thread.current.to_s,
                             :state => "new")

      log = Log.create options

      if  !log.running?
        begin
          log.state = "running"
          log.save!

          yield log

          log.state = "completed"
        rescue Exception => e
          log.state = "error"
          log.error = e.message
          log.backtrace =  e.backtrace

        ensure
          log.finished_at = Time.now
          log.save!
        end
      else
        begin
          log.state = "ignored"
        rescue Exception => e
          log.state = "error"
          log.error = e.message
          log.backtrace =  e.backtrace
        ensure
          log.finished_at = Time.now
          log.save!
        end
      end

    end

    ##
    # Kills the job if running
    # Using PID
    ##
    def kill
      return false unless hostname == Socket.gethostname
      begin
        Process.kill('KILL', pid)
        self.state = "killed"
        self.save!
      rescue Errno::ESRCH
        puts "pid #{pid} does not exist!"
        mark_dead
      end
    end

    ##
    # Checks to see if the PID of the log is active or not
    ##
    def running?
      logs = Log.where(:file => file, 
                       :job_type => job_type, 
                       :state => "running",
                       :export_id => export_id,
                       :hostname => hostname)
  
      if logs.count > 0
        logs.each do |log|
          begin
            Process.getpgid(log.pid)
            puts "still running #{log.file}"
            return true
          rescue Errno::ESRCH
            log.mark_dead
          end
        end
      end
      
      return false
    end
    
    ##
    # Clear all logs marked running that have run for more than 2 hours
    ##
    def self.clear_stucks
      runnings = Log.where(:state => "running")
      news = Log.where(:state => "new")
      logs = runnings + news
      
      if logs.count > 0
        logs.each do |log|
          
          time_start = log.started_at
          now = Time.now()
          if time_start + 2.hour < now
            begin
              Process.kill('KILL', log.pid)
              log.state = "killed"
              log.save!
            rescue Errno::ESRCH
              log.state = "dead"
              log.save!
            end  
          end
        end
      end
      
    end

    
    ##
    # Clear all logs marked running that are not running
    ##
    def self.clear_deads
      logs = Log.where(:state => "running")
  
      if logs.count > 0
        logs.each do |log|
          begin
            Process.getpgid(log.pid) if log.hostname == Socket.gethostname
          rescue Errno::ESRCH
            log.mark_dead
          end
        end
      end
      
    end

    def self.clear_olds
      logs = Myreplicator::Log.where("started_at < date_sub(now(), interval 2 day)")
  
      if logs.count > 0
        logs.each do |log|
          begin
            log.destroy
          end
        end
      end
      
    end

    ##
    # Gets a jobtype, file and export_id
    # returns true if the job is completed
    ##
    def self.completed? *args
      options = args.extract_options!
      log = Log.where(:export_id => options[:export_id],
                      :file => options[:file],
                      :job_type => options[:job_type]).last
      #Kernel.p "===== transport_complete? log ====="
      #Kernel.p log
      if log.nil?
        #return false
        # Bug: no log of tranporter job. Using return true for now
        return true
      else
        return true if log.state == "completed"
      end
      
      return false
    end

    def mark_dead
      self.state = "dead"
      self.save!
    end

  end
end

app/models/myreplicator/sweeper.rb
module Myreplicator
  class Sweeper

    @queue = :myreplicator_sweeper # Provided for Resque
    ##
    # Main method provided for resque
    # Reconnection provided for resque workers
    ##
    def self.perform
      Myreplicator::Log.clear_deads
      Myreplicator::Log.clear_stucks
      Myreplicator::Log.clear_olds
      ActiveRecord::Base.configurations.keys.each do |db|
        Myreplicator::VerticaLoader.clean_up_temp_tables(db)
      end

      #removing files that are left in the storage for more than 12 hours
      folders = [
        "#{Myreplicator.tmp_path}",
        "#{Myreplicator.configs[Myreplicator.configs.keys[1]]["ssh_tmp_dir"]}"
      ]

      folders.each do |folder|
        cmd = "find #{folder} -mmin +720"
        l = `#{cmd}`
        list = l.split(/\n/)
        list.each do |file|
          file.chomp!
          if File.file?(file)
            if (file.split('.').last == 'gz') || (file.split('.').last == 'json')
              puts "=== #{file}"
              File.delete(file)
            end
          end
        end
      end

    end

  end
end

app/models/myreplicator/transfer.rb
module Myreplicator
  class Transfer < ActiveRecord::Base
    # attr_accessible :title, :body
  end
end

app/models/myreplicator/vertica_export.rb
module Myreplicator
  class VerticaExport < ActiveRecord::Base
    # attr_accessible :title, :body
  end
end

app/controllers/myreplicator/application_controller.rb
module Myreplicator
  class ApplicationController < ActionController::Base
    before_filter :authenticated?
    
    private 
    
    def authenticated?
      Kernel.p Myreplicator.auth_required
      if Myreplicator.auth_required
        puts request.fullpath
        url = "#{Myreplicator.login_redirect}?redirect_url=#{request.fullpath}"
        redirect_to url unless Myreplicator.authenticated
      end
    end
    
  end
end

app/controllers/myreplicator/exports_controller.rb
require_dependency "myreplicator/application_controller"

module Myreplicator

  class ExportsController < ApplicationController
    before_filter :tab
    helper_method :sort_column, :sort_direction
    # GET /exports
    # GET /exports.json
    def index
      @exports = Export.paginate(:page => params[:page]).order(sort_column + " " + sort_direction)
      @export = Export.first
      @dbs = get_dbs
      @search = Export.first
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @exports }
      end
      
    end
    
    def search
      Kernel.p params
      export_to = params[:export_to]
      table_name = params[:table_name]
      @exports = Export.paginate(:page => params[:page]).where("table_name LIKE '%#{table_name}%'")
      Kernel.p @exports.size 
      @search = Export.first
      @dbs = get_dbs
      @export = Export.first
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @exports }
      end
    end
  
    # GET /exports/1
    # GET /exports/1.json
    def show
      @export = Export.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @export }
      end
    end
  
    # GET /exports/new
    # GET /exports/new.json
    def new
      @export = Export.new
      @dbs = get_dbs
      @tables = db_metadata
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @export }
      end
    end
  
    # GET /exports/1/edit
    def edit
      @export = Export.find(params[:id])
      @dbs = get_dbs
      @tables = db_metadata
      @edit = true
    end
  
    # POST /exports
    # POST /exports.json
    def create
      @export = Export.new(params[:export])
      @dbs = get_dbs
      respond_to do |format|
        if @export.save
          format.html { redirect_to @export, notice: 'Export was successfully created.' }
          format.json { render json: @export, status: :created, location: @export }
          Myreplicator::Export.schedule_in_resque # schedule in resque
        else
          format.html { render action: "new" }
          format.json { render json: @export.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PUT /exports/1
    # PUT /exports/1.json
    def update
      @export = Export.find(params[:id])
      @dbs = get_dbs
  
      respond_to do |format|
        if @export.update_attributes(params[:export])
          format.html { redirect_to @export, notice: 'Export was successfully updated.' }
          format.json { head :no_content }
          Myreplicator::Export.schedule_in_resque # schedule in resque
        else
          format.html { render action: "edit" }
          format.json { render json: @export.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /exports/1
    # DELETE /exports/1.json
    def destroy
      @export = Export.find(params[:id])

      # remove from Resque
      Resque.remove_schedule(@export.schedule_name)

      @export.destroy

      respond_to do |format|
        format.html { redirect_to exports_url }
        format.json { head :no_content }
      end
    end
    
    def reload
      @export = Export.find(params[:id])
      flash[:notice] = "'#{@export.destination_schema}.#{@export.table_name}' is reloading"
      @export.reload
      redirect_to :action => 'index'
    end

  private

    def tab
      @tab = "exports"
    end
  
    def sort_column
      Export.column_names.include?(params[:sort]) ? params[:sort] : "source_schema"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
    def db_metadata
      @db_metadata ||= Myreplicator::Export.available_tables
    end

    def get_dbs
      return db_metadata.keys
    end

    def get_tables(db)
      return db_metadata[db]
    end
  end
end

app/controllers/myreplicator/home_controller.rb
require_dependency "myreplicator/application_controller"

module Myreplicator

  class HomeController < ApplicationController
    def index  
      @tab = 'home'
      @option = 'overview'
      @exports = Export.order('state DESC')
      @logs = Log.where(:state => 'running').order("id DESC")
      @now = Time.zone.now
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @exports }
      end
    end

    def export_errors
      @tab = 'home'
      @option = 'errors'
      @exports = Export.where("error is not null").order('source_schema ASC')    
      @logs = Log.where("state = 'error' AND job_type = 'export'").order("id DESC").limit(200)
      @count = Log.where("state = 'error' AND job_type = 'export'").count
    end
    
    def transport_errors
      @tab = 'home'
      @option = 'errors'
      @logs = Log.where("state = 'error' AND job_type = 'transporter'").order("id DESC").limit(200)
      @count = Log.where("state = 'error' AND job_type = 'transporter'").count
    end

    def load_errors
      @tab = 'home'
      @option = 'errors'
      @logs = Log.where("state = 'error' AND job_type = 'loader'").order("id DESC").limit(200)
      @count = Log.where("state = 'error' AND job_type = 'loader'").count
    end
    

    def kill
      @log = Log.find(params[:id])
      @log.kill
      redirect_to :action => 'index' 
    end
    
    def pause
      flash[:notice] = "Pause All DR Jobs"
      require 'rake'
      Rake::Task.load(Rails.root.to_s + "/lib/tasks/" + "maintenance.rake")
      resque_reload = Rake::Task['maintenance:stop_dr_jobs']
      resque_reload.reenable
      resque_reload.execute(ENV["RAILS_ENV"])
      @redis = Redis.new(:host => Settings[:redis][:host], :port => Settings[:redis][:port])
      @redis.set "under_maintenance", "true"
      redirect_to :action => 'index'
    end
        
    def resume
      flash[:notice] = "Resume All DR Jobs"
      require 'rake'
      Rake::Task.load(Rails.root.to_s + "/lib/tasks/" + "maintenance.rake")
      resque_reload = Rake::Task['maintenance:start_dr_jobs']
      resque_reload.reenable
      resque_reload.execute(ENV["RAILS_ENV"])
      @redis = Redis.new(:host => Settings[:redis][:host], :port => Settings[:redis][:port])
      @redis.set "under_maintenance", "false"
      redirect_to :action => 'index'
    end
  end
end

app/helpers/myreplicator/application_helper.rb
module Myreplicator
  module ApplicationHelper

    def sortable(column, title = nil)
      title ||= column.titleize
      css_class = column == sort_column ? "current #{sort_direction}" : nil
      direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
      link_to content_tag(:span, title), {:sort => column, :direction => direction}, {:class => css_class}
    end

    def chronos(secs)
      [[60, :seconds], [60, :minutes], [24, :hours], [1000, :days]].map{ |count, name|
        if secs > 0
          secs, n = secs.divmod(count)
          "#{n.to_i} #{name}"
        end
      }.compact.reverse.join(', ')
    end

    def export_err_count
      count = Log.where("state = 'error' AND job_type = 'export'").count
    end


    def run_count
      total = Log.where(:state => 'running').count
    end

    def loader_err_count
      count = Log.where("state = 'error' AND job_type = 'loader'").count
    end
    
    def transporter_err_count
      count = Log.where("state = 'error' AND job_type = 'transporter'").count
    end
    
    def under_maintenance
      #@redis = Redis.new(:host => 'localhost', :port => 6379)
      @redis = Redis.new(:host => Settings[:redis][:host], :port => Settings[:redis][:port])
      tmp = @redis.get "under_maintenance"
      puts tmp.class
      if tmp == "true"
        puts "===== ADASHKJDHJASKHDLASJLKDJALKS ====="
        puts tmp
        return true
      end
      return false
    end
    
  end
end

app/helpers/myreplicator/exports_helper.rb
module Myreplicator
  module ExportsHelper
  end
end

app/views/myreplicator/home/_home_menu.erb
<% 
  err1 = export_err_count
  err2 = loader_err_count
  err3 = transporter_err_count 
  run = run_count
  um = under_maintenance
%>
<%if um == true%> <div id="maint-message">The site is currently under maintanence</div> <% end %>
<div class="home-menu">
  <span>lists:</span>
  <a href="<%= root_url %>" class="<% if @option == 'overview' %>on<% end %> overview">overview <% if run > 0 %><span><%= run %></span><% end %></a>
  <a href="<%= export_errors_path %>" class="<% if @option == 'errors' %>on<% end %>">export errors <% if err1 > 0 %><span><%= err1 %></span><% end %></a>
  <a href="<%= transport_errors_path %>" class="<% if @option == 'errors' %>on<% end %>">transport errors <% if err3 > 0 %><span><%= err3 %></span><% end %></a>
  <a href="<%= load_errors_path %>" class="<% if @option == 'errors' %>on<% end %>">load errors <% if err2 > 0 %><span><%= err2 %></span><% end %></a>
</div>

app/views/myreplicator/home/errors.html.erb
<%= render :partial => 'home_menu' %>
<% @exports.each do |ex| %>
<div class="error-display">
  <span><em>table name:</em> <%= ex.table_name %></span>
  <span><em>source schema:</em><%=  ex.source_schema %></span>
  <span><em>updated at:</em><%= ex.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
  <span><em>error:</em></span>
  <pre><%= ex.error %></pre>
</div>
<% end %>
<% @logs.each do |log| %>
<div class="error-display">
  <span><em>name:</em> <%= log.name %></span>
  <span><em>file:</em> <%= log.file %></span>
  <span><em>type:</em> <%= log.job_type %></span>
  <span><em>started:</em> <%= log.started_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
  <span><em>error:</em></span>
  <pre><%= log.error %></pre>
</div>
<% end %>

app/views/myreplicator/home/export_errors.html.erb
<%= render :partial => 'home_menu' %>
<% @exports.each do |ex| %>
<div class="error-display">
  <span><em>table name:</em> <%= ex.table_name %></span>
  <span><em>source schema:</em><%=  ex.source_schema %></span>
  <span><em>updated at:</em><%= ex.updated_at.strftime("%Y-%m-%d %H:%M") %></span>
  <span><em>error:</em></span>
  <pre><%= ex.error %></pre>
</div>
<% end %>
<% @logs.each do |log| %>
<div class="error-display">
  <span><em>name:</em> <%= log.name %></span>
  <span><em>file:</em> <%= log.file %></span>
  <span><em>type:</em> <%= log.job_type %></span>
  <span><em>started:</em> <%= log.started_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
  <span><em>error:</em></span>
  <pre><%= log.error %></pre>
</div>
<% end %>

app/views/myreplicator/home/index.html.erb
<%= render :partial => 'home_menu' %>
<div id="overview-wrapper">
<h6>Running tasks</h6>
<table class="overview">
  <% @logs.each do |log| %>
  <tr>
    <td>
      <span class="name"><%= log.name %></span>
      <span class="file"><%= log.file %></span>
    </td>
    <td><%= log.state %></td>
    <td><%= log.job_type %></td>
    <td><%= log.started_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
    <td><%= chronos(@now.to_i - log.started_at.to_i) %></td>
    <td><%= link_to 'kill job', kill_path(log), :class => 'kill'%></td>
  </tr>
  <% end %>
</table>





</div>
<script>
jQuery(function(){
  var toggles = jQuery("a.state-toggle");
  toggles.click(function(e){
    e.preventDefault();
    var link = $(this);
    toggles.removeClass("on");
    link.addClass("on");
    jQuery(link.attr('href')).fadeIn().siblings("li").hide();
  })
  $("a.kill").click(function(e){
    if(confirm("Are you sure you wish to kill this running job?")!=true){e.preventDefault();}
  })
})
</script>

app/views/myreplicator/home/load_errors.html.erb
<%= render :partial => 'home_menu' %>
<% @logs.each do |log| %>
<div class="error-display">
  <span><em>name:</em> <%= log.name %></span>
  <span><em>file:</em> <%= log.file %></span>
  <span><em>type:</em> <%= log.job_type %></span>
  <span><em>started:</em> <%= log.started_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
  <span><em>error:</em></span>
  <pre><%= log.error %></pre>
</div>
<% end %>

app/views/myreplicator/home/transport_errors.html.erb
<%= render :partial => 'home_menu' %>

<% @logs.each do |log| %>
<div class="error-display">
  <span><em>name:</em> <%= log.name %></span>
  <span><em>file:</em> <%= log.file %></span>
  <span><em>type:</em> <%= log.job_type %></span>
  <span><em>started:</em> <%= log.started_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
  <span><em>error:</em></span>
  <pre><%= log.error %></pre>
</div>
<% end %>